<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
>
	<channel>
		<title><![CDATA[Themen - Bewerbung - DLRP.eu | Dein Roleplay Server]]></title>
		<link><![CDATA[https://forum.dlrp.eu/forum/]]></link>
		<description><![CDATA[]]></description>
		<language>de</language>
		<pubDate>Sun, 27 Nov 2022 07:31:43 +0000</pubDate>
		<lastBuildDate>Fri, 25 Nov 2022 16:43:39 +0000</lastBuildDate>
		<ttl>60</ttl>
		<generator><![CDATA[WoltLab Suite 5.4.24]]></generator>
		<atom:link href="https://forum.dlrp.eu/forum/index.php?board-feed/29/" rel="self" type="application/rss+xml" />
		<item>
			<title><![CDATA[Meine LSMD Bewerbung Von Viktor Carter]]></title>
			<link><![CDATA[https://forum.dlrp.eu/forum/index.php?thread/11897-meine-lsmd-bewerbung-von-viktor-carter/]]></link>
			<description><![CDATA[Sehr geehrter Herr Carter,<br><br><strong><span style="font-size: 18pt;"><span style="color:rgb(255,140,0);">Ihre Bewerbung wird nun bearbeitet!</span><span style="color:rgb(255,0,0);"><span></span></span></span></strong><br><br><span style="color:rgb(255,160,122);"><span style="font-size: 16px;"><strong><span style="color:rgb(255,255,255);">Wir bitten um etwas Geduld.</span></strong></span></span>]]></description>
			<pubDate>Fri, 25 Nov 2022 16:43:39 +0000</pubDate>
			<dc:creator><![CDATA[palontras]]></dc:creator>
			<guid><![CDATA[https://forum.dlrp.eu/forum/index.php?thread/11897-meine-lsmd-bewerbung-von-viktor-carter/]]></guid>
						<content:encoded><![CDATA[<p>Sehr geehrter Herr Carter,</p><p><br></p><p><strong><span style="font-size: 18pt;"><span style="color:rgb(255,140,0);">Ihre Bewerbung wird nun bearbeitet!</span><span style="color:rgb(255,0,0);"><span></span></span></span></strong></p><p><br></p><p><span style="color:rgb(255,160,122);"><span style="font-size: 16px;"><strong><span style="color:rgb(255,255,255);">Wir bitten um etwas Geduld.</span></strong></span></span></p>]]></content:encoded>
						<slash:comments><![CDATA[1]]></slash:comments>
		</item>
		<item>
			<title><![CDATA[Bewerbungsrichtlinien LSMD [25.12.2021] BITTE LESEN!!!]]></title>
			<link><![CDATA[https://forum.dlrp.eu/forum/index.php?thread/7942-bewerbungsrichtlinien-lsmd-25-12-2021-bitte-lesen/]]></link>
			<description><![CDATA[<span style="font-size: 30pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><strong><img src="https://cdn.discordapp.com/attachments/924090588540850228/924090608547672104/LSMD_Banner1.png" alt="LSMD_Banner1.png" class="jsResizeImage"></strong></span></span></span><br><span style="color:rgb(0,0,0);"><span style="font-family:Lobster, cursive;"><span style="font-size: 30pt;"><u>Bewerbun<span style="font-family:Georgia, serif;"></span>gsrichtlinien</u></span></span></span><br><br><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><br></span></span><br><span style="font-size: 20pt;"><span style="color:#FFFFFF;"><strong><span style="font-family:Georgia, serif;"><u>Allgemeine Voraussetzungen</u></span></strong></span></span><br><ul><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Mindestalter 15 Jahre</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">flüssige/r deutsche/r Sprachgebrauch und Rechtschreibung</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Bitte nutzen Sie das Freitextfeld – Google-Docs werden abgelehnt</span></span></span></li></ul>
<span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><br><br></span></span><strong><span style="font-size: 20pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><u>MD-Dienst-Voraussetzungen</u></span></span></span></strong><br><ul><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">EHK-/Pkw-Lizenz</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"></span></span></span></li></ul>…]]></description>
			<pubDate>Sat, 25 Dec 2021 00:01:01 +0000</pubDate>
			<dc:creator><![CDATA[Sebastian Snow]]></dc:creator>
			<guid><![CDATA[https://forum.dlrp.eu/forum/index.php?thread/7942-bewerbungsrichtlinien-lsmd-25-12-2021-bitte-lesen/]]></guid>
						<content:encoded><![CDATA[<p><span style="font-size: 30pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><strong><img src="https://cdn.discordapp.com/attachments/924090588540850228/924090608547672104/LSMD_Banner1.png" alt="LSMD_Banner1.png" class="jsResizeImage"></strong></span></span></span></p><p><span style="color:rgb(0,0,0);"><span style="font-family:Lobster, cursive;"><span style="font-size: 30pt;"><u>Bewerbun<span style="font-family:Georgia, serif;"></span>gsrichtlinien</u></span></span></span></p><p><br></p><p><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><br></span></span></p><p><span style="font-size: 20pt;"><span style="color:#FFFFFF;"><strong><span style="font-family:Georgia, serif;"><u>Allgemeine Voraussetzungen</u></span></strong></span></span></p><ul><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Mindestalter 15 Jahre</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">flüssige/r deutsche/r Sprachgebrauch und Rechtschreibung</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Bitte nutzen Sie das Freitextfeld – Google-Docs werden abgelehnt</span></span></span></li></ul>
<p><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><br><br></span></span><strong><span style="font-size: 20pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><u>MD-Dienst-Voraussetzungen</u></span></span></span></strong></p><ul><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">EHK-/Pkw-Lizenz</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Weiterbildungsbereitschaft</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Keine registrierten Akteneinträge für mindestens zwei Wochen</span></span></span></li></ul>
<p><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><br><br></span></span><strong><span style="font-size: 20pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><u>Sozialkompetenz</u></span></span></span></strong></p><ul><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Teamfähigkeit</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Pünktlichkeit</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Hilfsbereitschaft</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Freundlichkeit</span></span></span></li></ul>
<p><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><br><br></span></span><strong><span style="font-size: 20pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"><u>Struktur der Bewerbung</u></span></span></span></strong></p><ul><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Anschreiben OOC</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Anschreiben IC</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Lebenslauf</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Stärken und Schwächen</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Steckbrief (Ausweisdaten in Schriftform)</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Onlinezeiten / Erreichbarkeit</span></span></span></li><li><span style="font-size: 15pt;"><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;">Schlusswort</span></span></span></li></ul>
<p><br></p><p><strong><span style="font-family:Georgia;"><span style="font-size: 20pt;"><span style="color:#FFF0F5;"><u>Was bieten wir Ihnen?</u></span></span></span></strong></p><p><span style="font-family:Georgia;"><span style="font-size: 15pt;"><span style="color:#FFF0F5;">Neben einem vielseitigen und spannenden Beruf erwartet Sie ein gut gelauntes Team, welches immer herzlichst neue Mitglieder aufzunehmen vermag. Team-building-Maßnahmen, wie z.B. ein “Paintball”-Event im vergangenen Jahr, sind auch ein aufstrebender Trend. Ein freundliches und organisiertes Arbeitsklima gilt für uns als Selbstverständlichkeit.</span></span></span></p><p><span style="font-family:Georgia;"><span style="font-size: 15pt;"><span style="color:#FFF0F5;">Abseits davon erwartet sie ein attraktives steigerbares Gehalt, welches zudem noch durch zahlreiche Provisionszahlungen für absolvierte Dienstleistungen gut ergänzt wird. </span></span></span><span style="color:rgb(255,240,245);font-size: 15pt;font-family:Georgia;">Des Weiteren können Sie sich über einige Vorteile wie etwa einer Blitzer-Befreiung, Tankgutscheinen, Austeilung von Reparatur-Kits oder sonstige Bonuszahlungen.</span></p><p><span style="color:#FFF0F5;"><br><br></span></p><p><span style="font-family:Georgia;"><span style="font-size: 15pt;"><span style="color:#FFF0F5;">Mit freundlichen Grüßen</span></span></span></p><p><span style="color:#FFF0F5;"><br><br></span></p><p><span style="font-family:Georgia;"><span style="font-size: 15pt;"><span style="color:#FFF0F5;">Die Personalleitung</span></span></span></p><p><span style="font-family:Georgia;"><span style="font-size: 12pt;"><span style="color:#FFF0F5;">(Chiefs/Personalmanager)</span></span></span></p><p><br></p><p><br></p><p><span style="color:#FFFFFF;"><span style="font-family:Georgia, serif;"></span></span></p>]]></content:encoded>
						<slash:comments><![CDATA[0]]></slash:comments>
		</item>
	</channel>
</rss>